# Generated by Django 5.0.2 on 2024-03-03 09:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pos', models.CharField(max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='Sentence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('sentence', models.CharField(max_length=100)),
                ('eng', models.CharField(default='1', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Word',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('word', models.CharField(max_length=40)),
                ('public', models.BooleanField(default=True)),
                ('antonym_words', models.ManyToManyField(blank=True, related_name='antonym_word', to='fasariona.word')),
                ('related_words', models.ManyToManyField(blank=True, related_name='related_word', to='fasariona.word')),
            ],
        ),
        migrations.CreateModel(
            name='Description',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('definition', models.CharField(max_length=100)),
                ('note', models.TextField(blank=True, null=True)),
                ('pos', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pos_desc', to='fasariona.pos')),
                ('sentences', models.ManyToManyField(blank=True, related_name='sentence_desc', to='fasariona.sentence')),
                ('word', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='desc', to='fasariona.word')),
            ],
        ),
    ]
