# Generated by Django 5.0.2 on 2024-03-03 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fasariona', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='WikiNote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(blank=True, max_length=40, null=True)),
                ('content', models.TextField(blank=True, null=True)),
                ('public', models.BooleanField(default=True)),
                ('related_notes', models.ManyToManyField(blank=True, related_name='notes_related', to='fasariona.wikinote')),
            ],
        ),
    ]
