# Generated by Django 5.0.2 on 2024-03-09 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fasariona', '0002_wikinote'),
    ]

    operations = [
        migrations.AddField(
            model_name='wikinote',
            name='order_num',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
